### ISSUE TITLE
Not compiling under Fedora 40

### ISSUE THREAD

**Issue by Plutonium5793** [olegkutkov/Raw2Fits#3]
I have been trying to get this going, and have installed all the dependencies.   The make file does not seem to be able to find them either for the gui or the command line version.   I would appreciate any help in getting this running.

**Comment by olegkutkov** [comment]
Hello. Could you please build log?

**Comment by Plutonium5793** [comment]
I just installed fedora 41.  I will attempt to compile and get back to you with the results.  Thanks,
John

**Comment by Plutonium5793** [comment]
I started make and got these results.  Both libraw and libconfig are installed.  I tried putting PKG_CONFIG_PATH in to the directory where I found libraw.pc, but it still didn't find it.   I am out of my depth here to do more.

jduchek@HP-K:~/Raw2Fits$ make
Package libraw was not found in the pkg-config search path.
Perhaps you should add the directory containing `libraw.pc'
to the PKG_CONFIG_PATH environment variable
Package 'libraw' not found
Package libconfig was not found in the pkg-config search path.
Perhaps you should add the directory containing `libconfig.pc'
to the PKG_CONFIG_PATH environment variable
Package 'libconfig' not found
Package 'libraw' not found
Package libraw was not found in the pkg-config search path.
Perhaps you should add the directory containing `libraw.pc'
to the PKG_CONFIG_PATH environment variable
Package 'libraw' not found
cc  -Wall -pipe -I./include -g -ggdb src/converter.c src/list.c src/file_utils.c src/thread_pool.c src/raw2fits.c src/coords_calc.c src/main.c  -lm -lpthread -export-dynamic -o raw2fits
src/file_utils.c: In function ‘make_target_fits_filename’:
src/file_utils.c:154:25: warning: ‘strncpy’ output truncated before terminating nul copying 1 byte from a string of the same length [-Wstringop-truncation]
  154 |                         strncpy(out_file_name_base + raw_filename_len - 4, "_", 1);
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/file_utils.c:179:25: warning: ‘strncpy’ output truncated before terminating nul copying 1 byte from a string of the same length [-Wstringop-truncation]
  179 |                         strncpy(out_file_name_base + obj_len, "_", 1);
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/file_utils.c:211:25: warning: ‘strncpy’ output truncated before terminating nul copying 1 byte from a string of the same length [-Wstringop-truncation]
  211 |                         strncpy(out_file_name_base + obj_len, "_", 1);
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/file_utils.c:213:25: warning: ‘strncpy’ output truncated before terminating nul copying 1 byte from a string of the same length [-Wstringop-truncation]
  213 |                         strncpy(out_file_name_base + obj_len + filter_len + 1, "_", 1);
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/raw2fits.c:25:10: fatal error: fitsio.h: No such file or directory
   25 | #include <fitsio.h>
      |          ^~~~~~~~~~
compilation terminated.
src/coords_calc.c: In function ‘deg_to_sexigesimal_str’:
src/coords_calc.c:121:34: warning: ‘%.5f’ directive output may be truncated writing between 3 and 316 bytes into a region of size between 0 and 10 [-Wformat-truncation=]
  121 |         snprintf(buf, 14, "%i:%i:%.5f", hour, min, sec);
      |                                  ^~~~
src/coords_calc.c:121:27: note: assuming directive output of 7 bytes
  121 |         snprintf(buf, 14, "%i:%i:%.5f", hour, min, sec);
      |                           ^~~~~~~~~~~~
src/coords_calc.c:121:9: note: ‘snprintf’ output between 8 and 340 bytes into a destination of size 14
  121 |         snprintf(buf, 14, "%i:%i:%.5f", hour, min, sec);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/coords_calc.c: In function ‘coordinates_to_sexigesimal_str’:
src/coords_calc.c:141:34: warning: ‘%i’ directive output may be truncated writing between 1 and 6 bytes into a region of size between 0 and 10 [-Wformat-truncation=]
  141 |         snprintf(dst, 14, "%i:%i:%i.%i", hour, min, sec, msec);
      |                                  ^~
src/coords_calc.c:141:27: note: directive argument in the range [-32768, 32767]
  141 |         snprintf(dst, 14, "%i:%i:%i.%i", hour, min, sec, msec);
      |                           ^~~~~~~~~~~~~
src/coords_calc.c:141:27: note: directive argument in the range [-32768, 32767]
src/coords_calc.c:141:9: note: ‘snprintf’ output between 8 and 28 bytes into a destination of size 14
  141 |         snprintf(dst, 14, "%i:%i:%i.%i", hour, min, sec, msec);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/main.c:22:10: fatal error: gtk/gtk.h: No such file or directory
   22 | #include <gtk/gtk.h>
      |          ^~~~~~~~~~~
compilation terminated.
make: *** [Makefile:62: all] Error 1
jduchek@HP-K:~/Raw2Fits$

**Comment by olegkutkov** [comment]
Thank you. I will install Fedora 41 to get back with the proper build manual.

**Comment by olegkutkov** [comment]
Please, run the following command: `sudo yum install gcc LibRaw-devel libconfig-devel cfitsio-devel gtk3-devel`
Then `make` Raw2Fits.

It's successfully compiled on my Fedora
![image](https://github.com/user-attachments/assets/adb61072-8372-4f86-8448-73ebee679c70)

**Comment by Plutonium5793** [comment]
Yes, worked like a champ.  Thank you very much.  
John

**Comment by olegkutkov** [comment]
Great!
Also, make sure you are using the latest code version. I fixed a minor bug yesterday.
Now you can run `sudo make install`, and it should be installed and shown in the Fedora applications menu.
